on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Gradle Build Action
        # You may pin to the exact commit or the version.
        # uses: gradle/gradle-build-action@ac2d340dc04d9e1113182899e983b5400c17cda1
        uses: gradle/actions/setup-gradle@v4
        with:
          # Gradle version to use. If specified, this Gradle version will be downloaded, added to the PATH and used for invoking Gradle.
          # If not provided, it is assumed that the project uses the Gradle Wrapper.
          gradle-version: '8.8'

      - name: Assemble the project
        run: gradle assemble

      - name: Run the tests
        run: gradle test
          
      
