on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build with Gradle
      # You may pin to the exact commit or the version.
      # uses: gradle/actions@af1da67850ed9a4cedd57bfd976089dd991e2582
      uses: gradle/actions@v4.0.0
      with:
        arguments: --scan
      
