on:
  push:
    branches:
    - main

jobs:
  file-list:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Download tree
        run: sudo apt install tree
      - name: List everything
        run: tree /
        
