on:
  push:
    branches:
    - main

jobs:
  file-list:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.7
      - name: Download tree
        run: sudo apt install tree
      - name: List everything
        run: tree /home/runner/work/KotlinJsonParser/KotlinJsonParse
        
